import { Partner, Category } from "../types";

// ============================================================
// BRAND
// ============================================================
export const BRAND_COLORS = {
  primary: "#E63946",
  secondary: "#1A1A1A",
  accent: "#F59E0B",
  background: "#FFFFFF",
  cardBg: "#F8F8F8",
  textPrimary: "#1A1A1A",
  textSecondary: "#6B7280",
};

export const CATEGORIES: Category[] = [
  "food", "cafe", "fitness", "shopping", "entertainment", "beauty", "culture", "services"
];

export const CATEGORY_EMOJIS: Record<string, string> = {
  food: "🍔",
  cafe: "☕",
  fitness: "💪",
  shopping: "🛍️",
  beauty: "💅",
  culture: "🎭",
  entertainment: "🎮",
  services: "🔧"
};

export const CATEGORY_LABELS: Record<string, string> = {
  food: "Essen",
  cafe: "Café",
  fitness: "Fitness",
  shopping: "Shopping",
  beauty: "Beauty",
  culture: "Kultur",
  entertainment: "Unterhaltung",
  services: "Services"
};

// ============================================================
// MOCK PARTNERS (Offline / Dev mode)
// ============================================================
export const MOCK_PARTNERS: Partner[] = [
  {
    id: "d0a1b2c3-0001-4000-8000-000000000001",
    name: "Döner Palace",
    category: "food",
    location: "Zwickauer Str. 12",
    coordinates: { lat: 50.827, lng: 12.912 },
    image: "https://picsum.photos/seed/doner/800/600",
    description: "Der beste Döner in Chemnitz mit frischen Zutaten.",
    rating: 4.8,
    instagram: "donerpalace_chemnitz",
    stampsNeeded: 10,
    rewardTitle: "Gratis Döner",
    rewardDescription: "Ein Döner deiner Wahl komplett gratis!",
    briefFacts: ["Täglich frisch gebackenes Brot", "Geheimrezept für die Kräutersoße", "Über 20 Jahre Erfahrung"],
    isActive: true,
  },
  {
    id: "d0a1b2c3-0002-4000-8000-000000000002",
    name: "Café Roter Turm",
    category: "cafe",
    location: "Markt 1",
    coordinates: { lat: 50.833, lng: 12.921 },
    image: "https://picsum.photos/seed/cafe/800/600",
    description: "Traditionelles Café direkt am Wahrzeichen.",
    rating: 4.5,
    instagram: "caferoterturm",
    stampsNeeded: 8,
    rewardTitle: "Gratis Kaffee & Kuchen",
    rewardDescription: "Ein Heißgetränk + Kuchenstück gratis!",
    briefFacts: ["Bester Blick auf den Roten Turm", "Hausgemachte Torten nach Omas Rezept"],
    isActive: true,
  },
  {
    id: "d0a1b2c3-0003-4000-8000-000000000003",
    name: "Roter Turm Döner",
    category: "food",
    location: "Neumarkt, Chemnitz",
    coordinates: { lat: 50.832, lng: 12.922 },
    image: "https://picsum.photos/seed/roterdoner/800/600",
    description: "Frischer Döner direkt am Roten Turm.",
    rating: 4.7,
    instagram: "roterdoner_chemnitz",
    stampsNeeded: 8,
    rewardTitle: "Döner für 1€",
    rewardDescription: "Dein nächster Döner für nur 1 Euro!",
    briefFacts: ["Direkt am Roten Turm", "Frische Zutaten täglich"],
    isActive: true,
  },
  {
    id: "d0a1b2c3-0004-4000-8000-000000000004",
    name: "Feuerbiss",
    category: "food",
    location: "Chemnitz Innenstadt",
    coordinates: { lat: 50.834, lng: 12.917 },
    image: "https://picsum.photos/seed/feuerbiss/800/600",
    description: "Saftige Burger mit Feuer-Feeling.",
    rating: 4.6,
    instagram: "feuerbiss_chemnitz",
    stampsNeeded: 10,
    rewardTitle: "Gratis Burger",
    rewardDescription: "Ein Signature Burger komplett gratis!",
    briefFacts: ["Hausgemachte Burger-Patties", "Scharfe Signature-Saucen"],
    isActive: true,
  },
  {
    id: "d0a1b2c3-0005-4000-8000-000000000005",
    name: "Hychinka Chemnitz",
    category: "food",
    location: "Chemnitz",
    coordinates: { lat: 50.829, lng: 12.919 },
    image: "https://picsum.photos/seed/hychinka/800/600",
    description: "Authentische Küche mit besonderem Flair.",
    rating: 4.8,
    instagram: "hychinka_chemnitz",
    stampsNeeded: 8,
    rewardTitle: "5€ Rabatt",
    rewardDescription: "5 Euro Rabatt auf deine nächste Bestellung!",
    briefFacts: ["Authentische Rezepte", "Familiäre Atmosphäre"],
    isActive: true,
  },
  {
    id: "d0a1b2c3-0006-4000-8000-000000000006",
    name: "Eisfenster Gloesa",
    category: "food",
    location: "Gloesa, Chemnitz",
    coordinates: { lat: 50.831, lng: 12.920 },
    image: "https://picsum.photos/seed/eisfenster/800/600",
    description: "Cremiges Eis aus eigener Herstellung.",
    rating: 4.9,
    instagram: "eisfenster_gloesa",
    stampsNeeded: 6,
    rewardTitle: "2 Kugeln gratis",
    rewardDescription: "Zwei Kugeln Eis deiner Wahl komplett gratis!",
    briefFacts: ["Über 20 hausgemachte Sorten", "Vegane Optionen"],
    isActive: true,
  },
  {
    id: "d0a1b2c3-0007-4000-8000-000000000007",
    name: "SportCity Chemnitz",
    category: "fitness",
    location: "Limbacher Str. 67",
    coordinates: { lat: 50.841, lng: 12.898 },
    image: "https://picsum.photos/seed/gym/800/600",
    description: "Modernes Fitnessstudio mit Sauna und Kursen.",
    rating: 4.7,
    instagram: "sportcity_chemnitz",
    stampsNeeded: 10,
    rewardTitle: "1 Woche gratis",
    rewardDescription: "Eine ganze Woche kostenloses Training!",
    briefFacts: ["Größte Saunalandschaft", "Über 50 Kurse pro Woche"],
    isActive: true,
  },
  {
    id: "d0a1b2c3-0008-4000-8000-000000000008",
    name: "Galerie Roter Turm",
    category: "shopping",
    location: "Neumarkt 2",
    coordinates: { lat: 50.832, lng: 12.923 },
    image: "https://picsum.photos/seed/shopping/800/600",
    description: "Das größte Shopping-Center im Herzen von Chemnitz.",
    rating: 4.4,
    instagram: "galerieroterturm",
    stampsNeeded: 12,
    rewardTitle: "5€ Shopping Gutschein",
    rewardDescription: "Fünf Euro Gutschein für alle Shops!",
    briefFacts: ["Über 60 Fachgeschäfte", "Zentraler Treffpunkt"],
    isActive: true,
  },
  {
    id: "d0a1b2c3-0009-4000-8000-000000000009",
    name: "Beauty Lounge",
    category: "beauty",
    location: "Theaterstr. 4",
    coordinates: { lat: 50.835, lng: 12.918 },
    image: "https://picsum.photos/seed/beauty/800/600",
    description: "Deine Oase für Entspannung und Schönheit.",
    rating: 4.9,
    instagram: "beautylounge_c",
    stampsNeeded: 8,
    rewardTitle: "Gratis Behandlung",
    rewardDescription: "Eine Basic-Behandlung komplett kostenlos!",
    briefFacts: ["Zertifizierte Naturkosmetik", "Individuelle Hautanalyse"],
    isActive: true,
  },
  {
    id: "d0a1b2c3-0010-4000-8000-000000000010",
    name: "Opernhaus Chemnitz",
    category: "culture",
    location: "Theaterplatz 2",
    coordinates: { lat: 50.838, lng: 12.924 },
    image: "https://picsum.photos/seed/opera/800/600",
    description: "Eines der modernsten Opernhäuser Deutschlands.",
    rating: 4.8,
    instagram: "theaterchemnitz",
    stampsNeeded: 6,
    rewardTitle: "2-für-1 Ticket",
    rewardDescription: "Zwei Tickets zum Preis von einem!",
    briefFacts: ["Prachtvoller Bau am Theaterplatz", "Vielfältiges Programm"],
    isActive: true,
  },
];

export const MOCK_TIPS = [
  "Poste eine Instagram-Story im Laden und bekomme einen Bonus-Stempel!",
  "Max. 4 Story-Stempel pro Laden pro Monat — plan sie clever ein!",
  "Je kleiner der Laden, desto schneller ist die Karte voll.",
  "Der Nischel wiegt 40 Tonnen — check mal ein am Opernhaus!",
];
